catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - client
overrides:
  jiti: ^2.6.1
catalog:
  '@antfu/eslint-config': ^6.6.1
  '@css-inline/css-inline': ^0.18.0
  '@headlessui/vue': ^1.7.23
  '@iconify-json/carbon': ^1.2.15
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/noto': ^1.2.7
  '@iconify-json/ri': ^1.2.6
  '@iconify-json/simple-icons': ^1.2.62
  '@iconify-json/tabler': ^1.2.23
  '@img/sharp-linux-x64': ^0.34.5
  '@nuxt/content': ^3.9.0
  '@nuxt/devtools': ^3.1.1
  '@nuxt/devtools-kit': ^3.1.1
  '@nuxt/devtools-ui-kit': ^3.1.1
  '@nuxt/icon': ^2.1.0
  '@nuxt/image': ^2.0.0
  '@nuxt/kit': ^4.2.2
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/test-utils': ^3.21.0
  '@nuxt/ui': ^4.2.1
  '@nuxtjs/color-mode': ^4.0.0
  '@nuxtjs/eslint-config-typescript': ^12.1.0
  '@nuxtjs/i18n': ^10.2.1
  '@nuxtjs/tailwindcss': ^6.14.0
  '@resvg/resvg-js': ^2.6.2
  '@resvg/resvg-wasm': ^2.6.2
  '@unocss/core': ^66.5.10
  '@unocss/nuxt': ^66.5.10
  '@unocss/preset-icons': ^66.5.10
  '@unocss/preset-wind3': ^66.5.10
  '@unocss/runtime': ^66.5.10
  '@vueuse/core': ^14.1.0
  '@vueuse/nuxt': ^14.1.0
  better-sqlite3: ^12.5.0
  bumpp: ^10.3.2
  chrome-launcher: ^1.2.1
  consola: ^3.4.2
  defu: ^6.1.4
  eslint: ^9.39.1
  execa: ^9.6.1
  floating-vue: ^5.2.2
  globby: ^16.0.0
  happy-dom: ^20.0.11
  image-size: ^2.0.2
  jest-image-snapshot: ^6.5.1
  json-editor-vue: ^0.18.1
  magic-string: ^0.30.21
  mocked-exports: ^0.1.1
  nuxt: ^4.2.2
  nuxt-site-config: ^3.2.11
  nypm: ^0.6.2
  ofetch: ^1.5.1
  ohash: ^2.0.11
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  playwright: ^1.57.0
  playwright-core: ^1.57.0
  radix3: ^1.1.2
  sass: ^1.96.0
  satori: ^0.18.3
  satori-html: ^0.3.2
  sharp: ^0.34.5
  shiki: ^3.19.0
  sirv: ^3.0.2
  splitpanes: ^4.0.4
  std-env: ^3.10.0
  strip-literal: ^3.1.0
  typescript: ^5.9.3
  ufo: ^1.6.1
  unocss: ^66.5.10
  unplugin: ^2.3.11
  unwasm: ^0.5.2
  vitest: ^4.0.15
  vue: ^3.5.25
  vue-router: ^4.6.4
  vue-tsc: ^3.1.8
  yoga-wasm-web: ^0.3.3

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - json-editor-vue
  - sharp
  - unrs-resolver
  - vue-demi
