catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - eslint-import-resolver-typescript@3.10.1
  - undici-types@6.21.0
  - semver@6.3.1
  - koa@2.16.3
  - semver@5.7.2
  - '@nuxtjs/tailwindcss@7.0.0-beta.1'
packages:
  - playground
  - client
overrides:
  vite: npm:vite@8.0.0-beta.13

catalog:
  '@antfu/eslint-config': ^7.6.1
  '@clack/prompts': ^1.0.1
  '@iconify-json/carbon': ^1.2.19
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/noto': ^1.2.7
  '@iconify-json/ri': ^1.2.10
  '@iconify-json/tabler': ^1.2.28
  '@img/sharp-linux-x64': ^0.34.5
  '@nuxt/content': ^3.12.0
  '@nuxt/devtools': ^3.2.2
  '@nuxt/devtools-kit': ^3.2.2
  '@nuxt/devtools-ui-kit': ^3.2.2
  '@nuxt/fonts': ^0.14.0
  '@nuxt/icon': ^2.2.1
  '@nuxt/image': ^2.0.0
  '@nuxt/kit': ^4.3.1
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/test-utils': ^4.0.0
  '@nuxt/ui': ^4.5.0
  '@nuxtjs/color-mode': ^4.0.0
  '@nuxtjs/eslint-config-typescript': ^12.1.0
  '@nuxtjs/i18n': ^10.2.3
  '@nuxtjs/tailwindcss': 7.0.0-beta.1
  '@resvg/resvg-js': ^2.6.2
  '@resvg/resvg-wasm': ^2.6.2
  '@tailwindcss/vite': ^4.2.1
  '@takumi-rs/core': ^0.69.5
  '@takumi-rs/wasm': ^0.69.5
  '@vitejs/plugin-vue': ^6.0.4
  '@vue/compiler-sfc': ^3.5.29
  '@vueuse/core': ^14.2.1
  '@vueuse/nuxt': ^14.2.1
  better-sqlite3: ^12.6.2
  birpc: ^4.0.0
  bumpp: ^10.4.1
  chrome-launcher: ^1.2.1
  consola: ^3.4.2
  culori: ^4.0.2
  defu: ^6.1.4
  devalue: ^5.6.3
  eslint: ^10.0.2
  exsolve: ^1.0.8
  fontless: ^0.2.1
  get-image-colors: ^4.0.1
  globby: ^16.1.1
  happy-dom: ^20.7.0
  jest-image-snapshot: ^6.5.1
  lightningcss: ^1.31.1
  magic-string: ^0.30.21
  magicast: ^0.5.2
  mocked-exports: ^0.1.1
  nuxt: ^4.3.1
  nuxt-site-config: ^3.2.21
  nypm: ^0.6.5
  ofetch: ^1.5.1
  ohash: ^2.0.11
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  playwright: ^1.58.2
  playwright-core: ^1.58.2
  radix3: ^1.1.2
  sass: ^1.97.3
  satori: 0.19.2
  sharp: ^0.34.5
  sirv: ^3.0.2
  std-env: ^3.10.0
  strip-literal: ^3.1.0
  tailwindcss: ^4.2.1
  tinyexec: ^1.0.2
  tinyglobby: ^0.2.15
  typescript: ^5.9.3
  ufo: ^1.6.3
  ultrahtml: ^1.6.0
  unifont: ^0.7.4
  unplugin: ^3.0.0
  vitest: ^4.0.18
  vue: ^3.5.29
  vue-router: ^5.0.3
  vue-tsc: ^3.2.5
  wrangler: ^4.69.0
  yoga-wasm-web: ^0.3.3
catalogs:
  devtools:
    '@iconify-json/simple-icons': ^1.2.71
    json-editor-vue: ^0.18.1
    shiki: ^4.0.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - json-editor-vue
  - sharp
  - unrs-resolver
  - vue-demi
