catalogMode: prefer

cleanupUnusedCatalogs: true

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - eslint-import-resolver-typescript@3.10.1
  - undici-types@6.21.0
  - semver@6.3.1
  - koa@2.16.3
  - semver@5.7.2
  - '@nuxtjs/tailwindcss@7.0.0-beta.1'
packages:
  - playground
  - client
overrides:
  vite: npm:vite@8.0.0-beta.2

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@clack/prompts': ^1.0.0
  '@css-inline/css-inline': ^0.19.2
  '@css-inline/css-inline-wasm': ^0.19.2
  '@headlessui/vue': ^1.7.23
  '@iconify-json/carbon': ^1.2.18
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/noto': ^1.2.7
  '@iconify-json/ri': ^1.2.9
  '@iconify-json/simple-icons': ^1.2.69
  '@iconify-json/tabler': ^1.2.26
  '@img/sharp-linux-x64': ^0.34.5
  '@nuxt/content': ^3.11.0
  '@nuxt/devtools': ^3.1.1
  '@nuxt/devtools-kit': ^3.1.1
  '@nuxt/devtools-ui-kit': ^3.1.1
  '@nuxt/fonts': ^0.13.0
  '@nuxt/icon': ^2.2.1
  '@nuxt/image': ^2.0.0
  '@nuxt/kit': ^4.3.0
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/test-utils': ^3.23.0
  '@nuxt/ui': ^4.4.0
  '@nuxtjs/color-mode': ^4.0.0
  '@nuxtjs/eslint-config-typescript': ^12.1.0
  '@nuxtjs/i18n': ^10.2.1
  '@nuxtjs/tailwindcss': ^7.0.0-beta.1
  '@resvg/resvg-js': ^2.6.2
  '@resvg/resvg-wasm': ^2.6.2
  '@tailwindcss/vite': ^4.1.18
  '@takumi-rs/core': ^0.66.13
  '@takumi-rs/wasm': ^0.66.13
  '@vitejs/plugin-vue': ^6.0.4
  '@vue/compiler-sfc': ^3.5.27
  '@vueuse/core': ^14.2.0
  '@vueuse/nuxt': ^14.2.0
  better-sqlite3: ^12.6.2
  birpc: ^4.0.0
  bumpp: ^10.4.0
  chrome-launcher: ^1.2.1
  consola: ^3.4.2
  culori: ^4.0.2
  defu: ^6.1.4
  devalue: ^5.6.2
  eslint: ^9.39.2
  execa: ^9.6.1
  exsolve: ^1.0.8
  get-image-colors: ^4.0.1
  globby: ^16.1.0
  happy-dom: ^20.5.0
  image-size: ^2.0.2
  jest-image-snapshot: ^6.5.1
  jiti: ^2.6.1
  json-editor-vue: ^0.18.1
  magic-string: ^0.30.21
  magicast: ^0.5.1
  mocked-exports: ^0.1.1
  nuxt: ^4.3.0
  nuxt-site-config: ^3.2.19
  nypm: ^0.6.4
  ofetch: ^1.5.1
  ohash: ^2.0.11
  pathe: ^2.0.3
  pkg-types: ^2.3.0
  playwright: ^1.58.1
  playwright-core: ^1.58.1
  postcss: ^8.5.6
  postcss-calc: ^10.1.1
  postcss-custom-properties: ^15.0.0
  radix3: ^1.1.2
  sass: ^1.97.3
  satori: 0.19.1
  satori-legacy: npm:satori@0.15.2
  sharp: ^0.34.5
  shiki: ^3.22.0
  sirv: ^3.0.2
  std-env: ^3.10.0
  strip-literal: ^3.1.0
  tailwindcss: ^4.1.18
  tinyglobby: ^0.2.15
  typescript: ^5.9.3
  ufo: ^1.6.3
  ultrahtml: ^1.6.0
  unplugin: ^3.0.0
  unwasm: ^0.5.3
  vitest: ^4.0.18
  vue: ^3.5.27
  vue-router: ^5.0.2
  vue-tsc: ^3.2.4
  wrangler: ^4.61.1
  yoga-wasm-web: ^0.3.3
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - json-editor-vue
  - sharp
  - unrs-resolver
  - vue-demi
